name: upcom-your-tab
version: 0.1.0
authors:
- Your Name <your@email.com>
description: A custom tab for UpDroid Commander
homepage: https://www.yourwebsite.com
environment:
  sdk: '>=1.9.3 <2.0.0'
dependencies:
  upcom-api: '>=0.5.3 <0.6.0'
  quiver: any
