name: upcom-speak
version: 0.1.0
authors:
- Your Name <mike@updroid.com>
description: An UpCom Tab for robot text-to-speech.
homepage: https://www.updroid.com
environment:
  sdk: '>=1.9.3 <2.0.0'
dependencies:
  upcom-api: '>=0.5.3 <0.6.0'
  quiver: any
